name: Run Python Tests and flake 8
on:
  #push:
  #  branches:
  #    - main    
  pull_request:
    branches:
      - main

jobs: 
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # se copia el codigo en la maquina que se esta ejecutando esto

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6 #instala python 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt #instala los requirements

      - name: Run flake8 #ejecuta flake8
        run: flake8 .

      - name: Run tests with pytest #ejecuta pytest
        run: pytest

#https://github.com/marketplace/actions/up-merge
